### ISSUE TITLE
Investigate <task> Element

### ISSUE THREAD

**Issue by tomschr** [openSUSE/geekodoc#1]
_From @tomschr on November 11, 2015 12:13_

DocBook5 brings a [`<task>`](http://www.docbook.org/tdg51/en/html/task.html) element which could help us in some regards.

Implement it in HTML and FO.

Related to openSUSE/daps#254.

_Copied from original issue: openSUSE/suse-xsl#94_

**Comment by tomschr** [comment]
Discussed with Stefan, Tanja and Frank:

* a required `title` inside `task`.
* `taskrelated`: `para` (and maybe `formalpara`) is needed
* `tasksummary`: paragraphs, lists, figures, and tables
* `taskprerequisites`: `para` (and maybe `formalpara`) is needed

@sknorr: Anything to add or misunderstood?

**Comment by sknorr** [comment]
Two additions: 

tasksummary: + admons
taskrelated: + lists
