### ISSUE TITLE
Fix content model for step to allow para substeps para

### ISSUE THREAD

**Issue by tomschr** [openSUSE/geekodoc#12]
Taken from openSUSE/daps#383

The idea from Tanja is: allow inside [`step`](http://docbook.org/tdg51/en/html/step.html) para after a substep.

The question is: should we allow this? Can a para after a substep easily be overlooked?

**Comment by tomschr** [comment]
the GeekoDoc version in this repo allows `para` as a sibling of `substep`. We should fix this for Novdoc...

**Comment by tomschr** [comment]
Related to #14, so it's already fixed.

**Comment by sknorr** [comment]
@tomschr Have you communicated your changes here with Rich and Arul? This seems like a compatibility issue with their version of NovDoc and very likely their stylesheets too.

**Comment by tomschr** [comment]
@sknorr Not yet, but I planned to do so.
