### ISSUE TITLE
Make sure GeekoDoc is available in OBS/IBS, so we can use it from DC files

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#33]
We are currently holding off on putting the GeekoDoc schema in our DC files, because it is not available in OBS. Instead, we are relying on all our editors to install GeekoDoc on their machines on their own.

This makes it harder for new team members and external editors (e.g. for AY or OBS docs) to create GeekoDoc-compliant documentation.

**Comment by tomschr** [comment]
I think, we can close this. Some submit requests for this:

* https://build.opensuse.org/request/show/574639
* https://build.suse.de/request/show/154390
