### ISSUE TITLE
Create semi-official XML Schema

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#40]
Visual Studio Code with IBM's XML extension allows using XSD but not RNG. Could an (approximate) XSD version of the schema be provided as well?

**Comment by tomschr** [comment]
I'm not sure if this is really possible. It can  be difficult as RNG allows some content models which are not allowed in XSD.
There is a reason why the DocBook team abandomed the creation of XSDs... 😉

**Comment by sknorr** [comment]
FTR, StackOverflow points at `java -jar trang.jar -I rnc -O xsd test.rnc test.xsd`... (Which toms already tried with not so much success, I think.)

**Comment by tomschr** [comment]
I've tried to convert it and got the following messages:

```
$ trang -I rnc -O xsd geekodoc5-flat.rnc geekodoc5-flat.xsd

geekodoc5-flat.rnc:333:9: warning: cannot represent required wildcard attribute; approximating
geekodoc5-flat.rnc:338:37: warning: choice between attributes and children cannot be represented; approximating
geekodoc5-flat.rnc:7713:51: warning: choice between attributes and children cannot be represented; approximating
geekodoc5-flat.rnc:7772:51: warning: choice between attributes and children cannot be represented; approximating
/geekodoc5-flat.rnc:10923:5: warning: cannot represent required wildcard attribute; approximating
```

However, I don't know if the XSD is really usable. Opening the XSD file in oXygen gives me lots of validation errors. 😏

I guess, it isn't really of much use. Writing a XSD file is hard and maintaining it even harder. 😉 Well, I can add it to the build chain and integrate it into our geekodoc package, but I guess, nobody would be really happy about that.

Can you try that for Visual Studio Code and see if it works? If you can confirm it works I'm fine and will integrate it. If it doesn't work, I don't see any value of adding that. 

Personally, I try to stay away from XSDs as much as I can. 😆

**Comment by tomschr** [comment]
I think, this is not really going to work, so closing for the time being. If you still think, it's a good idea to have a XSD, feel free to reopen the issues.

**Comment by sknorr** [comment]
I agree with prioing this "low" -- but I think it would be good to keep this open, because it would more or less instantly buy us not insignificant editor support.

**Comment by tomschr** [comment]
I've tried it, same error messages with GeekoDoc v2. It takes significant resources and knowledge to create a XSD schema. Not happening now, so closing.
