### ISSUE TITLE
Move Novdoc into a maintenance Branch

### ISSUE THREAD

**Issue by tomschr** [openSUSE/geekodoc#57]
## Problem Description

As Novdoc is considered obsolete, we should adapt the repository structure.

## Expected Behaviour

Remove all Novdoc related files or move them into a specific maintenance branch.

**Comment by tomschr** [comment]
This is solved with the [1.0.4 release](https://github.com/openSUSE/geekodoc/releases/tag/v1.0.4) and commit ba186bc3963

**Comment by sknorr** [comment]
This really was not much of an enhancement ... now I need to switch branch before I can look at the Novdoc schema. :/
