### ISSUE TITLE
Reduce content model of command

### ISSUE THREAD

**Issue by tomschr** [openSUSE/geekodoc#59]
## Problem Description

In version 1.0.2.1 of GeekoDoc, `command` allows the following child elements:

```
alt, annotation, date, emphasis, firstterm, footnote, foreignphrase,
glossterm, indexterm, inlinemediaobject, link, phrase, quote, remark,
replaceable, subscript, superscript, trademark, xref.
```

This is too broad, we need a reduced content model.

## Expected Behaviour

Reduce it to `emphasis`(?), `phrase`, `replaceable`

**Comment by sknorr** [comment]
<emphasis> can be useful, to highlight specific parts of a command. This is used quite a bit in the SOC documentation that we got from HPE.
