### ISSUE TITLE
Unorthodox book structures are now legal

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#62]
Novdoc prevented book structures like:

```
book id=A
  - part
  - preface
  - part
  - chapter
  - part
```

It would only allow structures like:

```
book id=B
  - preface
  - chapter
  - part
  - part
  - part
```

Geekodoc allows both and imo it should only allow the structure of book B.

**Comment by tomschr** [comment]
Merged with commit 5859e1d, so closing.
