### ISSUE TITLE
Disallow empty sections

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#64]
The following is currently allowed in Geekodoc:

```
<section>
  <title>Some title</title>
 </section>
```

(Same issue for `<sect[1-5]/>`)

Imo, sections should always contain at least either:

* actual content (`<para/>`/...)
* a subsection

I wouldn't make a para or similar mandatory if there is a subsection, even if that is the ideal case. But in the past, doing so has only led authors to include empty `<para/>` tags that then created layout issues to circumvent that rule.

**Comment by tomschr** [comment]
Well, seems disable some element patterns leads to this issue.

Currently, the original definition of a `section` is as follows:

```
db.section =
    ## A recursive section
   element section {
      db.section.attlist,
      db.section.info,
      db.navigation.components*,
      db.recursive.blocks.or.sections?,
      db.navigation.components*
    }
```

Seems, either in the `db.navigation.components` or the `db.recursive.blocks.or.sections` patterns aren't "enough" elements available. Investigating further.
