### ISSUE TITLE
Reduce content model of replaceable

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#69]
replaceable allows the following nested content:

```
alt, annotation, co, date, emphasis, firstterm, footnote, foreignphrase, glossterm,
indexterm, inlinemediaobject, link, phrase, quote, remark, subscript, superscript,
trademark, xref,
text
```
i'd suggest to reduce that to just `emphasis`, `phrase`, text.

**Comment by tomschr** [comment]
I assume, that applies to `phrase` and `emphasis` as well, right?

**Comment by sknorr** [comment]
Well, `phrase` really can't be reduced by much (because we literally use it as a container for inlines). `emphasis` is probably a similar case and can't be reduced by much. So :/ :(, I guess.

**Comment by tomschr** [comment]
> Well, phrase really can't be reduced by much...

Are you really sure? I haven't customized `phrase` yet, so it contains everything that is not disabled. When I look what `phrase` offers to me, I get the above elements plus some more.

So either oXygen lies to me or we talk about different phrases. :wink:

**Comment by sknorr** [comment]
> Are you really sure? I haven't customized `phrase` yet, so it contains everything that is not disabled.

Maybe read the part I put in parentheses as well?:

> (because we literally use it as a container for inlines)

Meaning: there is a lot of stuff in phrase but we probably want all the stuff because we need phrase as a random container for profiling purposes.

**Comment by tomschr** [comment]
Oh, sorry, I misread your sentence and got the opposite meaning from what you've wrote. Argh.

In that case, I agree with you. We can't reduce these two. Ok, will tackle `replaceable` only.

**Comment by tomschr** [comment]
@sknorr better? :wink:
If you don't object, I would merge these changes (seems pretty easy and straightforward).
