### ISSUE TITLE
Use <mediaobject/> only?

### ISSUE THREAD

**Issue by taroth21** [openSUSE/geekodoc#7]
In one of our XML files, I found the following code: 

```
 <mediaobject>
  <imageobject>
   <imagedata width="50%" fileref="hawk-batchmode-show.png"/>
  </imageobject>
 </mediaobject>
```

It can currently be validated with GeekoDoc and works as expected in PDF (and also in EPUB output). However the question is if we really want to allow this in GeekoDoc (without `<figure/>` or `<informalfigure/>` and also without the `role` attribute that we usually use?

**Comment by tomschr** [comment]
As discussed with Tanja:

* we allow `mediaobject` only inside `figure` and `informalfigure`
* we disallow `xml:id` attribute in `informalfigure`
* we leave `role` untouched
