### ISSUE TITLE
Expand test cases to include as many of our actual documents as possible

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#70]
I was just wondering -- if we built and sync'd bigfiles to susedoc.github.io and had Travis download them as part of the Geekodoc test cases, we could immediately see if & how much breakage any change of Geekodoc is creating.

That would aid *a lot* in estimating whether a particular change that seems like a good idea in theory is also a good idea in practice.

In the past I sometimes did that manually (i.e. installing the new Geekodoc version and running `for dc in DC-*; do daps -d $dc validate; done`) but that really does not scale.

This would need two primary changes:

* Addition of a bigfile build to openSUSE/doc-ci's `travis.sh`
* Addition of a couple of `wget` commands to the test cases of this repo

**Comment by tomschr** [comment]
Good idea! I think, it would be a valuable addition.

Currently, we have "good" and "bad" tests. The latter validate usually structures which shouldn't be there -- they are expected to fail (which is a good thing).

> In the past I sometimes did that manually (i.e. installing the new Geekodoc version and running for dc in DC-*; do daps -d $dc validate; done) but that really does not scale.

Hehe, I did the same!

One questions:

* Should Travis validate against the `develop` or `master` branch or both?
* Should we "restrict" our testcases to some dedicated repos only?
  (I know, the more we test, the better we cover all cases. However, from a practical point of view, there are maybe only 5-8 repos needed to keep it small and fast.)

**Comment by sknorr** [comment]
>     * Should Travis validate against the `develop` or `master` branch or both?

My idea was to put readily compiled bigfiles into a special directory Travis's publishing repos like https://github.com/susedoc/doc-sle and to do that for *all* the documentation that Travis is currently building for us.

Using the special directory has the advantage that we don't need to clone content via Git which means the tests should run much quicker (cloning 

>     * Should we "restrict" our testcases to some dedicated repos only?
>       (I know, the more we test, the better we cover all cases. However, from a practical point of view, there are maybe only 5-8 repos needed to keep it small and fast.)

Speed is one of my concerns as well, but:

1. the repos we "need" "most" also contain the biggest guides (i.e. doc-sle)
2. it's not particularly fair to put some colleagues's needs before those others

**Comment by tomschr** [comment]
> > * Should Travis validate against the `develop` or `master` branch or both?
>
> My idea was to put readily compiled bigfiles into a special directory Travis's publishing repos like https://github.com/susedoc/doc-sle and to do that for all the documentation that Travis is currently building for us.

Maybe I wasn't clear enough. I was more referring to Geekodoc's  `develop` or `master` branch, not for the doc-* repos. :smile_cat: 

Having `master` checked against (all?) doc repos is probably useful to validate against the stable Geekodoc release. On the other side, it may be too late, so `develop` would be useful to catch some errors earlier. Hmn... :thinking:

**Comment by sknorr** [comment]
When it's already on master it's indeed likely too late. I'd almost want it in pull requests already.

**Comment by tomschr** [comment]
We focus on our normal test cases in the `tests` directory for the time being.
