### ISSUE TITLE
<info/> can contain multiple <date/> tags

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#74]
So, related to [AsciiDoc writing its own dates into documents](https://github.com/openSUSE/daps/issues/521), it became apparent that GeekoDoc allows multiple \<date/\> elements in the \<info/\> element.

Is there a good reason to allow this? (E.g. different kinds of dates?)

Note that it might not be ideal to forbid this right now, exactly because AsciiDoctor is writing this stuff out and we don't really want to rile everyone up by invalidating their documents. opensuse/daps#521 needs to be fixed first here and then when a fix is out we could update the schema.

**Comment by tomschr** [comment]
It's not a bug, it's a feature. Meike needs it to distinguish between publishing dates and dates where the document was last updated.
