### ISSUE TITLE
Release geekodoc 2.0.0

### ISSUE THREAD

**Issue by tomschr** [openSUSE/geekodoc#76]
## Problem Description

We need to release Geekodoc 2.0.0, but need to maintain the 1.x.y line.

## Checklist

Discussed with @sknorr 

* [x] Correct Git repo layout and create these two new directories:
  * `geekodoc/5.1-1/`: means, based on DocBook 5.1 with Geekodoc 1.a.b
  * `geekodoc/5.1-2/`: means, based on DocBook 5.1 with Geekodoc 2.x.y
* [x] Create customization layer for Geekodoc 2 with all the changes for 2.x.y.
* [x] Create new catalog entries for Geekodoc 2, but still keep the old ones.
* [x] Create new `geekodoc` package with version 2.0.0:
  * Create two new directories (similar to the directories for DocBook):
     * `/usr/share/xml/geekodoc/rng/5.1-1/`
     * `/usr/share/xml/geekodoc/rng/5.1-2/`
  * Create link from `/usr/share/xml/geekodoc/rng/geekodoc5-flat.rn?` to `/usr/share/xml/geekodoc/rng/5.1-1/geekodoc1-flat.rn?`.
* [x] Create separate `novdoc` package.

Anything else that I forgot and should be included in the list?

**Comment by sknorr** [comment]
List looks good. :)

**Comment by tomschr** [comment]
A first beta 4 is available at https://build.opensuse.org/package/show/home:thomas-schraitle:branches:Documentation:Tools/geekodoc

I had to deviate a bit from the directory structure: `5.1-1` or `5.1-2` becomes `<GEEKODOC_VERSION>-<DOCBOOK_VERSION>`. In that case, we have `1-5.1` and `2-5.2`. I think, this is more logical, as GeekoDoc version is the differentiator and not DocBook.

**Comment by tomschr** [comment]
GeekoDoc v2.0.0 is available on Documentation:Tools now.
