### ISSUE TITLE
Allow guilabel

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#78]
Geekodoc currently only allows the guimenu element. Unfortunately, that element's name is not really conveying that you should also use it for labels in a UI.

Imo, it would be ideal if we could remove guimenu entirely and replace it with guilabel in the schema. "label" is just much more general and makes more sense for pretty much all UI elements with text on them. guilabel is also allowed as an element of menuchoice, so that use case is covered too.

However, entirely outlawing it might be too big of a change -- unless, maybe as part of the 2.0 version that you are working on already. If we have wider buy-in from the team, it might be possible to add this change too.

Otherwise, I would just be in favor of adding guilabel to the schema.

**Comment by tomschr** [comment]
Makes sense. I also didn't like the semantic inaccuracy of `guimenu`.

I think, adding it for the 2.0 version would be a good idea. If the team would like to have it for the 1.x release, we could backport it too.

**Comment by cwickert** [comment]
Can we move forward with this one? Ideally also for 1.x?!

I was about to file an issue for allowing guimenuitem. It's like guimenu, but in a terminal. This does not make sense. And it does not work for YaST, where we don't know whether the user is running the qt or ncurses version. So I'm all for using guilabel everywhere (or as much as possible).

**Comment by tomschr** [comment]
i don't think removing `<guimenu>` makes sense. Adding `<guilabel>` is a good idea. The mentioned PR takes that into account and adds this element.
