### ISSUE TITLE
Support for "section"

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#8]
GeekoDoc (like NovDoc) does not support the `<section/>` tag that is used in the release notes of both SLE (still DB4-based) and openSUSE (already DB5-based). Given how deeply entrenched the section tag is in our release notes tooling, we probably will not switch to using sect1/2/3/4/5 tags.

Given the complicated availability situation of the GeekoDoc schema, that creates some validation issues for me that ultimately mean that I can't use GeekoDoc in production anywhere:
- GeekoDoc is not part of any relevant build service project (i.e. not in Leap 42.2, not in SLE 12 SP2), so I can't put the requirement for GeekoDoc into any DC files.
- Release notes do not validate with GeekoDoc, so I can't put a requirement for it in my dapsrc either

---

And, then, on the virtues/non-disadavantages of section:
- section might be helpful in creating more re-usable documentation, since it can be nested within other sections (unlike sect1/2/3/4/5 where order is important).
- If we are introducing Schematron validation, then checking section would still not be an issue.

So, section support, is it in the cards?

**Comment by tomschr** [comment]
I see your point with re-usable documentation, but ATM I don't think we should allow `section` elements for our Geekdoc schema. I would like to keep Geekodoc as "easy" as possible. Especially, I try to avoid alternatives (like `sect1` vs. `section`, `para` vs. `simpara` etc.) as much as possible.

Couldn't you validate with DocBook5 instead? This should give you all the freedom. *If* validation with DocBook5 isn't the way you want it, we could create a separate schema especially for release notes. This would be based on Geekodoc, but enriched with `section` elements.

I close this bug, but if you like the second option, feel free to reopen it.
