### ISSUE TITLE
Disallow xml:id on listitems

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#80]
## Problem Description

The following is valid:

```
<ol>
  <listitem xml:id="sanna-marin"> ... </listitem>
</ol>
```

## Expected Behaviour

Since we can't create proper xref text from a listitem, xml:ids on them should be invalid. (Currently used in SOC 9 and SOC master docs.)

**Comment by tomschr** [comment]
Good catch! :+1: Agree, see #82 of my PR.
