### ISSUE TITLE
Disallow formal elements in admons

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#81]
*tbqh, I am not sure if this one is a duplicate -- it feels like it is, but I did not find another issue handling this.*

## Problem Description

This is currently valid:

```
<tip>
  <figure> ... </figure>
</tip>
```

[ I am not 100% sure whether the following is allowed but imo, formal element within formal element is a similar situation:

```
<procedure>
  <step>
    <para>...</para>
    <figure> ... </figure>
  </step>
</procedure>
```
]

## Expected Behaviour

Placing things that have a title themselves within an admon (or another formal element, like a procedure) is imo creating worse documents, because it aids in creating longer admonitions that may feel more like sections instead of concise ones about immediate practical issues/concerns. Ergo, formal items should be banned within them. (SES 6 and SES master are currently using this.)

**Comment by tomschr** [comment]
I agree, a `figure` inside a `tip` should be disallowed. Maybe an `informalfigure` could be useful.

The content model for admonitions are:

```
db.admonition.contentmodel = db._info.title.only, db.all.blocks+
```

I guess, we need to resolve `db.all.blocks` and list all the possible elements. Could be a bit cumbersome, but that would be a solution.

Regarding the `figure` inside `procedure`: yes, this is currently allowed. However, I don't see that as a big disadvantage. If I'm not mistaken, we use it occasionally.

**Comment by sknorr** [comment]
To me, figure in procedure makes no sense -- why not use informalfigures in this case? Procedures give a strong context anyway and so captioning your screenshot makes much less sense.

**Comment by tomschr** [comment]
> To me, figure in procedure makes no sense -- why not use informalfigures in this case?  Procedures give a strong context anyway and so captioning your screenshot makes much less sense.

True. Yes, I agree, from a layout perspective, it would be better to have `informalfigure` instead of `figure`.
The problem is, if we disallow `figure` in Geekodoc, a lot of SLE files won't validate anymore. Plus the maintenance and translation branches.

**Comment by tomschr** [comment]
The `tip/figure` may be still relevant, but this could be something for a custom Schematron rule. This is already taken into account in our styleguide.
