### ISSUE TITLE
Make it possible to define multiple products for the same document

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#87]
#### Problem Description

Within the SBP, there is often the issue that multiple products need to be described.
A related issue is that SBP often are designed to work for a range of versions of the same product (e.g. the same document may be valid for SLES-SAP 12 SP1, 12 SP2, and 12 SP3).
There is a general lack of structural support for this kind of thing. We only know the following two:

1. bog-standard:
    ```
    <info>
      <productname>PRODUCT</productname>
      <productnumber>1.0</productnumber>
    </info>
    ```

2. with an abbreviated product name in addition, like so:
    ```
    <info>
      <productname>PRODUCT</productname>
      <productname role="abbrev">PRODUCT</productname>
      <productnumber>1.0</productnumber>
    </info>
    ```

Crucially, we assume that both productname tags (both the plain variant and the variant woth role=abbrev) are different versions of spelling the _same_ product.
Another complication is that we allow inheritance of productname/productnumber from a set to its children books/articles and from a book to its children articles.

---

Afaik, @chabowski works around the issue either:

1. by using a subtitle for product versions:
    ```
    <info>
      <subtitle>PRODUCT_ONE 1.0, PRODUCT_TWO 1.3</subtitle>
    </info>
    ```
2. or by using a single productname and putting all information in there
    ```
    <info>
      <productname>PRODUCT_ONE 1.0, PRODUCT_TWO 1.3</productname>
    </info>
    ```

Which is pragmatic but not particularly semantic.

#### Expected Behavior

It would be great if we had a better option to map such realities onto our document, maybe even via the dm:docmanager tag set if DocBook does not work. I could imagine this:

1. single product:
    ```
   <info>
      <product><name>PRODUCT</name><nameabbrev>PRO</nameabbrev><number>1.0</number></product>
    </info>
    ```

2. multiple products:
    ```
    <info>
      <product><name>PRODUCT_ONE</name><number>1.0</number></product>
      <product><name>PRODUCT_TWO</name><number>1.0</number></product>
    </info>
   ```

3. ~multiple versions (I don't like it, just the best idea I had for now):~ [DON'T]
    ```
    <info>
      <product><name>PRODUCT_ONE</name><number>1.0</number><number>2.0</number></product>
    </info>
    ```

I mentioned inheritance of product names above and that is a bit of a complication here -- would product definitions in a specific book simply overwrite those from the set or would they add to the product definitions from the set?

**Comment by tomschr** [comment]
> would product definitions in a specific book simply overwrite those from the set or would they add to the product definitions from the set?

From my understanding yes. If you have an article inside book, those would be of higher priority than those inside of the book. The same applies for book in a set.

----

The structure in DocBook (and so GeekoDoc) is a bit unfortunate. The "bond" between productname and productnumber is very loose (it's actually non-existent).

Thanks for your ideas. I would like to through in some other ideas, based on what DocBook brings to the table. Maybe we can find some common ground.

I would first try to investigate if we can use the existing structure:


1. **Single product, multiple releases**
    In this case, you just list the product name and its releases like so:

      ```xml
      <info>
          <productname>SLES</productname>
          <productnumber>15 SP1</productnumber>
          <productnumber>15 SP2</productnumber>
          <productnumber>15 SP3</productnumber>
      </info>
      ```

2. **Multiple products, multiple releases (all products contain all releases)**
    This could maybe a special case. All products are published on all releases. We could use it like this:

      ```xml
      <info>
          <productname>SLES</productname>
          <productname>SLEHA</productname>
          <productnumber>15 SP1</productnumber>
          <productnumber>15 SP2</productnumber>
          <productnumber>15 SP3</productnumber>
      </info>
      ```

    In this case, the book is for SLES *and* SLEHA for the releases 15 SP1-SP3.

3. **Multiple products, multiple releases (every product has its own releases)**
    Obviously, this is the most challenging part. With multiple product we have the challenge, that the "bond" between product and release falls apart. We could use this: 

      ```xml
      <info>
          <productname>SLES</productname>
          <productname>SLEHA</productname>
          <productnumber>15 SP1</productnumber>
          <productnumber>15 SP2</productnumber>
          <productnumber>15 SP3</productnumber>

          <productname>SLES4SAP</productname>
          <productnumber>15 SP1</productnumber>
      </info>
      ```

   In the above case, this structure is for SLES and SLEHA for 15 SP1-SP3. For SLES4SAP it's only for 15 SP1. The stylesheet has to group and pick the necessary elements. Not so easy, but manageable.

Of course, it's not pretty, but maybe with some changes in some GeekoDoc content models and some stylesheet grouping, it could work.

---

If you don't like the above ideas, I could offer you another one. With the new DocBook 5.2 version we could use `<meta>`. Although semantically "empty/neutral", it may allow us to do whatever we want to do with it.

The downside is, it's name isn't very obvious for products and their releases. It's not very "writer-friendly". IMHO, the above `<productname>` and `<productnumber>` are easier to remember from a semantic point of view.

Additionally, the meta element isn't taken into account on titlepages.

**Comment by sknorr** [comment]
> The downside is, it's name isn't very obvious for products and their releases. It's not very "writer-friendly". IMHO, the above \<productname\> and \<productnumber\> are easier to remember from a semantic point of view.

Mmh. Imo, the productname/productnumber options you show above are not very writer-friendly either. And they also ignore the abbreviations we wanted to be able to add (and that we currently add via `<productname role="abbrev"/>`).

Given the options, I am ... almost in favor of extending the `dm:` namespace (or defining a new `suse:` namespace).

**Comment by sknorr** [comment]
Relevant for https://github.com/doc-suse-com/site/issues/53.

**Comment by sknorr** [comment]
Update: Bryan/Terry would also like a way to mark up partner products differently from SUSE products. They suggested (pseudo-code):

`<partnerprod/>` v. `<productname>`
