### ISSUE TITLE
Allow footnote

### ISSUE THREAD

**Issue by KucharczykL** [openSUSE/geekodoc#88]
## Problem Description

Creating footnotes in AsciiDoc (`footnote:title[text]`) is currently not allowed.

## Expected Behaviour

Using of footnotes is allowed.

@sknorr said it does not come out well in HTML but (without Geekodoc) I didn't see a problem. I can try helping with this one if pointed in the right direction.

**Comment by tomschr** [comment]
This is already the case in GeekoDoc v2. Enjoy your footnotes. :-)

**Comment by KucharczykL** [comment]
Very nice, thanks! Is there a way to try it out right now or is it neccessary to wait until 2.1.0 is released?

**Comment by tomschr** [comment]
Schema-wise the footnote element is already available in version 2.1.1. You can get it from OBS' Documentation:Tools.

What I haven't tried myself is how it is rendered (=the layout). Normally it should be taken into account from the upstream DocBook stylesheets. If something is screwed up, let me know and open an issue in openSUSE/suse-xsl. :slightly_smiling_face: Thanks!
