### ISSUE TITLE
Make chapter abstracts mandatory, restrict them to one para with 150 characters

### ISSUE THREAD

**Issue by ghost** [openSUSE/geekodoc#99]
## Description

Search engines like to show short descriptions, ideally 70-150 characters (meta description tag).

We'd like to not introduce too many different description elements, to avoid duplicating work here.
So, the idea we had in Stylewich was to use the `<abstract/>` element to do both: on-page abstract and meta description.
The stylesheets are already set up to funnel `<abstract/>` text into the meta description anyway, so Geekodoc 2 is the last piece of the puzzle to ensure some quality here.

## Expected Behavior

So what we want *in Geekodoc 2 only* is this:

* make `abstract` mandatory within `set`, `book`, `article`, `preface`, `part`, `chapter`, `appendix` and `topic`
* at least consider making `abstract` mandatory within top-level sections like `sect1`, `article/section` and `(preface|chapter|appendix)/section`
* enforce that there is a single `para` with only simple inline styling that converts well to plain-text within `abstract`s
* enforce that pure text content is at least 70 characters and at most 150 characters long -- I hope that's possible in RNG... You could definitely define a regex such as `.{70,150}` but I am not sure if that would run on pure text content or all content of the abstract.

cf. https://github.com/SUSE/doc-styleguide/pull/182

**Comment by tomschr** [comment]
We shouldn't restrict an abstract, it should be done with meta information. This is covered in #98 so this will be obsolete (and a wontfix issue).
